package com.jiyun.qcloud.dashixummoban.modle.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.qcloud.dashixummoban.modle.db.Gou;

import com.jiyun.qcloud.dashixummoban.modle.db.GouDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gouDaoConfig;

    private final GouDao gouDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gouDaoConfig = daoConfigMap.get(GouDao.class).clone();
        gouDaoConfig.initIdentityScope(type);

        gouDao = new GouDao(gouDaoConfig, this);

        registerDao(Gou.class, gouDao);
    }
    
    public void clear() {
        gouDaoConfig.clearIdentityScope();
    }

    public GouDao getGouDao() {
        return gouDao;
    }

}
